[package]
name = "kraken"
version = "0.1.0"
edition = "2024"

[dependencies]
csv = "1.3"
futures = "0.3.31"
ledger = { path = "crates/ledger" }
serde = "1.0.228"
tokio = { version = "1", features = ["rt", "rt-multi-thread", "macros"] }

[workspace]
members = ["crates/ledger"]
